# 1.16 错误处理

## 语法错误

通常是对运算符、表达式等使用不当造成的

```lua
a==2
```

```lua
1: syntax error near '=='
```

## 运行错误

程序可正常运行，但会输出错误信息

```lua
function add(a,b)
    return a+b
end
print(add(1,2))
print(add(1))
```

```lua
3
lua: ...orkSpace/LuaProjects/luaLearning/error/running_error.lua:2: attempt to perform arithmetic on a nil value (local 'b')
stack traceback:
	...orkSpace/LuaProjects/luaLearning/error/running_error.lua:2: in function 'add'
	...orkSpace/LuaProjects/luaLearning/error/running_error.lua:5: in main chunk
	[C]: in ?
```

此处时调用函数add参数不足，b由nil补全；nil参与运算导致的错误

## 错误处理

可使用两种函数进行错误处理，`assert`和`error`进行错误处理

###  `assert(v[,message])`

当v的值为nil或false时，assert将以message为错误信息抛出（默认为“assertion failed!”）

```lua
function add(a,b)
    assert(type(a)=="number","a is not type of number")
    assert(type(b)=="number","b is not type of number")
    return a+b
end
add(1,2)
add(1)
```

```lua
lua: ...WorkSpace/LuaProjects/luaLearning/error/assert_error.lua:3: b is not type of number
stack traceback:
	[C]: in function 'assert'
	...WorkSpace/LuaProjects/luaLearning/error/assert_error.lua:3: in function 'add'
	...WorkSpace/LuaProjects/luaLearning/error/assert_error.lua:7: in main chunk
	[C]: in ?
```

### `error (message [, level])`

终止正在执行的程序，并返回message的内容作为错误信息（error函数不会返回）

level参数指示获得错误得位置

* 1(默认): 调用error函数的位置（文件+行号）
* 2 ：指出调用error函数的函数的位置
* 0 ： 不添加错误位置信息

```lua
-- 使用error函数处理错误
function add(a,b)
    if type(a)~="number" then
        error("a is not type of number",2)
    end
end
add ("1",2)
```

```lua
lua: ...deWorkSpace/LuaProjects/luaLearning/error/error_func.lua:7: a is not type of number
stack traceback:
	[C]: in function 'error'
	...deWorkSpace/LuaProjects/luaLearning/error/error_func.lua:4: in function 'add'
	...deWorkSpace/LuaProjects/luaLearning/error/error_func.lua:7: in main chunk
	[C]: in ?
```

### `pcall (f [, arg1, ···])` 

传入函数名和函数参数，以保护模式调用函数f，`pcall`将会捕获函数f的错误

* 若未发生错误：返回true和函数返回结果
* 若发生错误：返回false和错误信息

```lua
-- 使用pcall进行错误处理
function divide(a,b )
    -- body
    assert(b~=0,"b cannot be 0")
    return a/b
end
print(pcall(divide,1,0))
```

```
false	...deWorkSpace/LuaProjects/luaLearning/error/pcall_test.lua:4: b cannot be 0
```

### `xpcall (f, msgh [, arg1, ···])`

与`pcall`类似，但是可额外设置消息处理器`msgh`

```lua
-- use xpcall
function divide(a,b )
    -- body
    assert(b~=0,"b cannot be 0")
    return a/b
end
function myErrorHandler(err)
    print("ERROR",err)
end
print(xpcall(divide,myErrorHandler,1,0))
```

```lua
ERROR	...eWorkSpace/LuaProjects/luaLearning/error/xpcall_test.lua:5: b cannot be 0
false	nil
```

